from django.urls import path
from .views import (
    dashboard, stat_cards, orders_table,
    order_detail, order_delete,
    order_quick_status, order_add_payment,
    order_cancel, order_approve_refund, pending_approvals,
    client_search, client_create_inline,
    order_form_view, order_item_row,
    payment_row, load_measurement_form,
    client_profile, client_edit,
    order_delivery_proof, export_csv,
    notifications_count, notifications_list,
    production_bill_view, production_bill_print,
    bill_toggle_sent,
    order_toggle_lock,
    order_reorder,
    upload_temp_photo,
    order_receipt_view,
    order_invoice_view,
    order_shipping_label_view,
)

app_name = "orders"

urlpatterns = [
    path("",                              dashboard,              name="dashboard"),
    path("cards/",                        stat_cards,             name="stat_cards"),
    path("orders-table/",                 orders_table,           name="orders_table"),
    path("new/",                          order_form_view,        name="order_add"),
    path("<int:pk>/edit/",                order_form_view,        name="order_edit"),
    path("<int:pk>/detail/",              order_detail,           name="order_detail"),
    path("<int:pk>/delete/",              order_delete,           name="order_delete"),
    path("<int:pk>/quick-status/",        order_quick_status,     name="order_quick_status"),
    path("<int:pk>/add-payment/",         order_add_payment,      name="order_add_payment"),
    path("<int:pk>/cancel/",              order_cancel,           name="order_cancel"),
    path("<int:pk>/approve-refund/",      order_approve_refund,   name="order_approve_refund"),
    path("<int:pk>/delivery-proof/",      order_delivery_proof,   name="order_delivery_proof"),
    path("<int:order_pk>/bill/<int:item_pk>/",
                                          production_bill_view,   name="production_bill"),
    path("bill/<int:pk>/print/",          production_bill_print,  name="production_bill_print"),
    path("bill/<int:pk>/sent/",           bill_toggle_sent,       name="bill_toggle_sent"),
    path("<int:pk>/lock-amount/",         order_toggle_lock,      name="order_toggle_lock"),
    path("<int:pk>/reorder/",             order_reorder,          name="order_reorder"),
    path("upload-temp-photo/",            upload_temp_photo,      name="upload_temp_photo"),
    path("<int:pk>/receipt/",             order_receipt_view,     name="order_receipt"),
    path("<int:pk>/invoice/",             order_invoice_view,     name="order_invoice"),
    path("<int:pk>/shipping-label/",      order_shipping_label_view, name="order_shipping_label"),
    path("pending-approvals/",            pending_approvals,      name="pending_approvals"),
    path("client/search/",                client_search,          name="client_search"),
    path("client/create-inline/",         client_create_inline,   name="client_create_inline"),
    path("client/<int:pk>/",              client_profile,         name="client_profile"),
    path("client/<int:pk>/edit/",         client_edit,            name="client_edit"),
    path("item-row/",                     order_item_row,         name="order_item_row"),
    path("payment-row/",                  payment_row,            name="payment_row"),
    path("load-measurement-form/",        load_measurement_form,  name="load_measurement_form"),
    path("export-csv/",                   export_csv,             name="export_csv"),
    path("notifications/",                notifications_list,     name="notifications_list"),
    path("notifications/count/",          notifications_count,    name="notifications_count"),
]