from django.urls import path
from .views import (
    dashboard, stat_cards, orders_table,
    order_detail, order_delete,
    order_quick_status, order_add_payment,
    order_cancel, order_approve_refund, pending_approvals,
    client_search, client_create_inline,
    order_form_view, order_item_row,
    payment_row, load_measurement_form,
    client_profile, client_edit,
    order_delivery_proof, export_csv, sales_report, service_worker,
    notifications_count, notifications_list,
    production_bill_view, production_bill_print,
    bill_toggle_sent,
    order_toggle_lock,
    order_reorder,
    upload_temp_photo,
    order_receipt_view,
    order_invoice_view,
    order_shipping_label_view,
    referred_by_search,
    status_board,
    inquiry_update,
    qr_generator,
    production_bill_pdf,
    production_bill_share,
    extract_contact_view,
    extract_measurements_view,
    scratch_pad_create,
    scratch_pad_tablet,
    scratch_pad_submit,
    scratch_pad_poll,
)
from orders.views_onboarding import onboarding_view, onboarding_success_view
from orders.views_external_number import check_external_order_number
from orders.views_fabric import (
    fabric_list, fabric_create, fabric_edit,
    fabric_delete, fabric_search,
)

app_name = "orders"

urlpatterns = [
    path("",                              dashboard,              name="dashboard"),
    path("cards/",                        stat_cards,             name="stat_cards"),
    path("orders-table/",                 orders_table,           name="orders_table"),
    path("new/",                          order_form_view,        name="order_add"),
    path("<int:pk>/edit/",                order_form_view,        name="order_edit"),
    path("<int:pk>/detail/",              order_detail,           name="order_detail"),
    path("<int:pk>/delete/",              order_delete,           name="order_delete"),
    path("<int:pk>/quick-status/",        order_quick_status,     name="order_quick_status"),
    path("<int:pk>/add-payment/",         order_add_payment,      name="order_add_payment"),
    path("<int:pk>/cancel/",              order_cancel,           name="order_cancel"),
    path("<int:pk>/approve-refund/",      order_approve_refund,   name="order_approve_refund"),
    path("<int:pk>/delivery-proof/",      order_delivery_proof,   name="order_delivery_proof"),
    path("<int:order_pk>/bill/<int:item_pk>/",
                                          production_bill_view,   name="production_bill"),
    path("bill/<int:pk>/print/",          production_bill_print,  name="production_bill_print"),
    path("bill/<int:pk>/pdf/",            production_bill_pdf,    name="production_bill_pdf"),
    path("bill/view/<uuid:token>/",       production_bill_share,  name="production_bill_share"),
    path("bill/<int:pk>/sent/",           bill_toggle_sent,       name="bill_toggle_sent"),
    path("<int:pk>/lock-amount/",         order_toggle_lock,      name="order_toggle_lock"),
    path("<int:pk>/reorder/",             order_reorder,          name="order_reorder"),
    path("upload-temp-photo/",            upload_temp_photo,      name="upload_temp_photo"),
    path("<int:pk>/receipt/",             order_receipt_view,     name="order_receipt"),
    path("<int:pk>/invoice/",             order_invoice_view,     name="order_invoice"),
    path("<int:pk>/shipping-label/",      order_shipping_label_view, name="order_shipping_label"),
    path("clients/search-referred/",      referred_by_search,        name="referred_by_search"),
    path("display/",                      status_board,              name="status_board"),
    path("pending-approvals/",            pending_approvals,      name="pending_approvals"),
    path("client/search/",                client_search,          name="client_search"),
    path("client/create-inline/",         client_create_inline,   name="client_create_inline"),
    path("client/<int:pk>/",              client_profile,         name="client_profile"),
    path("client/<int:pk>/edit/",         client_edit,            name="client_edit"),
    path("item-row/",                     order_item_row,         name="order_item_row"),
    path("payment-row/",                  payment_row,            name="payment_row"),
    path("load-measurement-form/",        load_measurement_form,  name="load_measurement_form"),
    path("export-csv/",                   export_csv,             name="export_csv"),
    path("sales/",                        sales_report,           name="sales_report"),
    path("sw.js",                         service_worker,         name="service_worker"),
    path("notifications/",                notifications_list,        name="notifications_list"),
    path("notifications/count/",          notifications_count,        name="notifications_count"),
    path("inquiry/<int:inquiry_id>/update/", inquiry_update,          name="inquiry_update"),
    path("qr/",                              qr_generator,            name="qr_generator"),
    path("bill/<int:pk>/print/",          production_bill_print,      name="production_bill_print"),
    path("bill/<int:pk>/pdf/",            production_bill_pdf,        name="production_bill_pdf"),
    path("bill/view/<uuid:token>/",       production_bill_share,      name="production_bill_share"),
    path("extract/contact/",              extract_contact_view,       name="extract_contact"),
    path("extract/measurements/",         extract_measurements_view,  name="extract_measurements"),
    path("scratch/create/",               scratch_pad_create,         name="scratch_pad_create"),
    path("scratch/<uuid:token>/",         scratch_pad_tablet,         name="scratch_pad_tablet"),
    path("scratch/<uuid:token>/submit/",  scratch_pad_submit,         name="scratch_pad_submit"),
    path("scratch/<uuid:token>/poll/",    scratch_pad_poll,           name="scratch_pad_poll"),
    path("onboarding/",                   onboarding_view,            name="onboarding"),
    path("onboarding/<str:subdomain>/success/", onboarding_success_view, name="onboarding_success"),
    path("check-external-number/", check_external_order_number, name="check_external_order_number"),
    # Fabric library
    path("fabrics/",                      fabric_list,                name="fabric_list"),
    path("fabrics/add/",                  fabric_create,              name="fabric_create"),
    path("fabrics/<int:pk>/edit/",        fabric_edit,                name="fabric_edit"),
    path("fabrics/<int:pk>/delete/",      fabric_delete,              name="fabric_delete"),
    path("fabrics/search/",               fabric_search,              name="fabric_search"),
]