services:
  web:
    build: .
    command: >
      gunicorn order_taking.wsgi:application
      --bind 0.0.0.0:8000
      --workers 3
      --timeout 120
    volumes:
      - .:/code
    ports:
      - "2222:8000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres_data: