services:

  web:
    command: sh -c "gunicorn order_taking.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 120"
    restart: always
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    expose:
      - "8000"
    environment:
      - DJANGO_SETTINGS_MODULE=order_taking.settings.prod
    depends_on:
      - db

  nginx:
    image: nginx:1.25.5
    restart: always
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/media
      - ./config/nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

  db:
    restart: always

volumes:
  static_volume:
  media_volume:
