# Generated by Django 5.2.11 on 2026-03-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_tenant',
            field=models.BooleanField(default=False),
        ),
    ]
