# Generated by Django 5.2.11 on 2026-03-04 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('postcode', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('contact_method', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('viber', 'Viber')], default='whatsapp', max_length=20)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('ready_date', models.DateField(blank=True, null=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'new'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('ready', 'Ready'), ('delivered', 'Delivered')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('measurement_model', models.CharField(help_text='Measurement model class name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BlouseMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoulder', models.FloatField(blank=True, null=True)),
                ('sleeve', models.FloatField(blank=True, null=True)),
                ('biceps', models.FloatField(blank=True, null=True)),
                ('chest', models.FloatField(blank=True, null=True)),
                ('hips', models.FloatField(blank=True, null=True)),
                ('front', models.FloatField(blank=True, null=True)),
                ('back', models.FloatField(blank=True, null=True)),
                ('high_chest', models.FloatField(blank=True, null=True)),
                ('waist', models.FloatField(blank=True, null=True)),
                ('upper_hips', models.FloatField(blank=True, null=True)),
                ('shoulder_to_middle_breast', models.FloatField(blank=True, null=True)),
                ('shoulder_to_under_breast', models.FloatField(blank=True, null=True)),
                ('middle_breast_to_middle_breast', models.FloatField(blank=True, null=True)),
                ('neck', models.FloatField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blouse', to='orders.basemeasurement')),
            ],
            options={
                'verbose_name': 'Blouse',
                'verbose_name_plural': 'Blouses',
            },
        ),
        migrations.CreateModel(
            name='CoatMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoulder', models.FloatField(blank=True, null=True)),
                ('sleeve', models.FloatField(blank=True, null=True)),
                ('biceps', models.FloatField(blank=True, null=True)),
                ('chest', models.FloatField(blank=True, null=True)),
                ('hips', models.FloatField(blank=True, null=True)),
                ('front', models.FloatField(blank=True, null=True)),
                ('back', models.FloatField(blank=True, null=True)),
                ('stomach', models.FloatField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coat', to='orders.basemeasurement')),
            ],
            options={
                'verbose_name': 'Coat',
                'verbose_name_plural': 'Coats',
            },
        ),
        migrations.CreateModel(
            name='DressMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoulder', models.FloatField(blank=True, null=True)),
                ('sleeve', models.FloatField(blank=True, null=True)),
                ('biceps', models.FloatField(blank=True, null=True)),
                ('chest', models.FloatField(blank=True, null=True)),
                ('hips', models.FloatField(blank=True, null=True)),
                ('front', models.FloatField(blank=True, null=True)),
                ('back', models.FloatField(blank=True, null=True)),
                ('high_chest', models.FloatField(blank=True, null=True)),
                ('waist', models.FloatField(blank=True, null=True)),
                ('upper_hips', models.FloatField(blank=True, null=True)),
                ('shoulder_to_middle_breast', models.FloatField(blank=True, null=True)),
                ('shoulder_to_under_breast', models.FloatField(blank=True, null=True)),
                ('middle_breast_to_middle_breast', models.FloatField(blank=True, null=True)),
                ('neck', models.FloatField(blank=True, null=True)),
                ('deep_front', models.FloatField(blank=True, null=True)),
                ('deep_back', models.FloatField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dress', to='orders.basemeasurement')),
            ],
            options={
                'verbose_name': 'Dress',
                'verbose_name_plural': 'Dresses',
            },
        ),
        migrations.CreateModel(
            name='JacketMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoulder', models.FloatField(blank=True, null=True)),
                ('sleeve', models.FloatField(blank=True, null=True)),
                ('biceps', models.FloatField(blank=True, null=True)),
                ('chest', models.FloatField(blank=True, null=True)),
                ('hips', models.FloatField(blank=True, null=True)),
                ('front', models.FloatField(blank=True, null=True)),
                ('back', models.FloatField(blank=True, null=True)),
                ('stomach', models.FloatField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jacket', to='orders.basemeasurement')),
            ],
            options={
                'verbose_name': 'Jacket',
                'verbose_name_plural': 'Jackets',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='orders.producttype')),
            ],
        ),
        migrations.AddField(
            model_name='basemeasurement',
            name='order_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='measurement', to='orders.orderitem'),
        ),
        migrations.CreateModel(
            name='OrderItemPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='order_item_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='orders.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='PantsMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waist', models.FloatField(blank=True, null=True)),
                ('hips', models.FloatField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('crotch', models.FloatField(blank=True, null=True)),
                ('thigh', models.FloatField(blank=True, null=True)),
                ('knee', models.FloatField(blank=True, null=True)),
                ('cuff', models.FloatField(blank=True, null=True)),
                ('belly', models.FloatField(blank=True, null=True)),
                ('base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pants', to='orders.basemeasurement')),
            ],
            options={
                'verbose_name': 'Pants',
                'verbose_name_plural': 'Pants',
            },
        ),
        migrations.CreateModel(
            name='ShirtMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoulder', models.FloatField(blank=True, null=True)),
                ('sleeve', models.FloatField(blank=True, null=True)),
                ('biceps', models.FloatField(blank=True, null=True)),
                ('chest', models.FloatField(blank=True, null=True)),
                ('hips', models.FloatField(blank=True, null=True)),
                ('front', models.FloatField(blank=True, null=True)),
                ('back', models.FloatField(blank=True, null=True)),
                ('neck', models.FloatField(blank=True, null=True)),
                ('stomach', models.FloatField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shirt', to='orders.basemeasurement')),
            ],
            options={
                'verbose_name': 'Shirt',
                'verbose_name_plural': 'Shirts',
            },
        ),
        migrations.CreateModel(
            name='ShortsMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waist', models.FloatField(blank=True, null=True)),
                ('hips', models.FloatField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('crotch', models.FloatField(blank=True, null=True)),
                ('thigh', models.FloatField(blank=True, null=True)),
                ('knee', models.FloatField(blank=True, null=True)),
                ('cuff', models.FloatField(blank=True, null=True)),
                ('belly', models.FloatField(blank=True, null=True)),
                ('base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shorts', to='orders.basemeasurement')),
            ],
            options={
                'verbose_name': 'Shorts',
                'verbose_name_plural': 'Shorts',
            },
        ),
        migrations.CreateModel(
            name='SkirtMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waist', models.FloatField(blank=True, null=True)),
                ('hips', models.FloatField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skirt', to='orders.basemeasurement')),
            ],
            options={
                'verbose_name': 'Skirt',
                'verbose_name_plural': 'Skirts',
            },
        ),
        migrations.CreateModel(
            name='VestMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoulder', models.FloatField(blank=True, null=True)),
                ('sleeve', models.FloatField(blank=True, null=True)),
                ('biceps', models.FloatField(blank=True, null=True)),
                ('chest', models.FloatField(blank=True, null=True)),
                ('hips', models.FloatField(blank=True, null=True)),
                ('front', models.FloatField(blank=True, null=True)),
                ('back', models.FloatField(blank=True, null=True)),
                ('stomach', models.FloatField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vest', to='orders.basemeasurement')),
            ],
            options={
                'verbose_name': 'Vest',
                'verbose_name_plural': 'Vests',
            },
        ),
        migrations.CreateModel(
            name='ClientPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_type', models.CharField(choices=[('front', 'Front'), ('side', 'Side'), ('back', 'Back')], max_length=20)),
                ('image', models.ImageField(upload_to='client_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_photos', to='orders.order')),
            ],
            options={
                'unique_together': {('order', 'photo_type')},
            },
        ),
    ]
