# Generated by Django 5.2.11 on 2026-06-11 08:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='departure_date',
            field=models.DateField(blank=True, help_text='Client departure date', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='hotel_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='room_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='type',
            field=models.CharField(choices=[('pickup', 'In-store Pickup'), ('hotel', 'Hotel Delivery'), ('ship', 'Ship to Address')], default='pickup', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Internal staff notes', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, help_text='Customer-facing (on invoice)', null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional — leave blank if price not yet confirmed', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
