# Generated by Django 5.2.11 on 2026-03-04 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuitMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoulder', models.FloatField(blank=True, null=True)),
                ('sleeve', models.FloatField(blank=True, null=True)),
                ('biceps', models.FloatField(blank=True, null=True)),
                ('chest', models.FloatField(blank=True, null=True)),
                ('hips', models.FloatField(blank=True, null=True)),
                ('front', models.FloatField(blank=True, null=True)),
                ('back', models.FloatField(blank=True, null=True)),
                ('waist', models.FloatField(blank=True, null=True)),
                ('crotch', models.FloatField(blank=True, null=True)),
                ('thigh', models.FloatField(blank=True, null=True)),
                ('knee', models.FloatField(blank=True, null=True)),
                ('cuff', models.FloatField(blank=True, null=True)),
                ('belly', models.FloatField(blank=True, null=True)),
                ('stomach', models.FloatField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suit', to='orders.basemeasurement')),
            ],
            options={
                'verbose_name': 'Suit',
                'verbose_name_plural': 'Suits',
            },
        ),
    ]
