# Generated by Django 5.2.11 on 2026-06-11 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_departure_date_order_hotel_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_currency',
            field=models.CharField(choices=[('THB', 'Thai Baht (THB)'), ('USD', 'US Dollar (USD)'), ('AUD', 'Australian Dollar (AUD)'), ('SGD', 'Singapore Dollar (SGD)'), ('EUR', 'Euro (EUR)'), ('crypto', 'Cryptocurrency')], default='THB', help_text='Currency of the quoted total amount', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='internal_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='parent_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_orders', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quoted price in the selected currency', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='exchange_rate_to_thb',
            field=models.DecimalField(decimal_places=6, default=1, help_text="THB=1. Crypto=agreed fixed rate. Others=today's rate.", max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('redeposit', 'Re-deposit'), ('balance', 'Balance'), ('full', 'Full Payment')], default='deposit', max_length=20),
        ),
    ]
