# Generated by Django 5.2.11 on 2026-03-07 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_suitmeasurement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScratchNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='scratch_notes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scratch_notes', to='orders.order')),
            ],
        ),
    ]
