# Generated by Django 5.2.11 on 2026-03-24 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.tenant'),
            preserve_default=False,
        ),
    ]
