# Generated by Django 5.2.11 on 2026-06-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_total_currency_alter_order_departure_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='marketing_consent',
            field=models.BooleanField(default=True, help_text='Client has consented to receive marketing communications (PDPA)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('redeposit', 'Re-deposit'), ('balance', 'Balance'), ('full', 'Full Payment'), ('refund', 'Refund')], default='deposit', max_length=20),
        ),
    ]
