# Generated by Django 5.2.11 on 2026-06-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_client_marketing_consent_alter_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='proof_image',
            field=models.ImageField(blank=True, help_text='Photo proof of delivery or shipping receipt', null=True, upload_to='delivery_proofs/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='proof_image',
            field=models.ImageField(blank=True, help_text='Proof of payment/refund (receipt, bank transfer screenshot, etc.)', null=True, upload_to='payment_proofs/'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('staff', 'Staff')], default='staff', help_text='Owner and Manager can modify staff assignments and approve refunds.', max_length=20),
        ),
    ]
