# Generated by Django 5.2.11 on 2026-06-14 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_delivery_proof_image_payment_proof_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_number', models.PositiveIntegerField(help_text='1, 2, 3 … matches quantity of OrderItem')),
                ('label', models.CharField(blank=True, help_text='Optional label e.g. "Groom", "Best Man"', max_length=100)),
            ],
            options={
                'verbose_name': 'Fabric Set',
                'verbose_name_plural': 'Fabric Sets',
                'ordering': ['bill', 'piece_number'],
            },
        ),
        migrations.CreateModel(
            name='TargetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Target Item',
                'verbose_name_plural': 'Target Items',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VariationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, help_text='Style diagram image shown on the production bill.', null=True, upload_to='variation_options/%Y/%m/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Variation Option',
                'verbose_name_plural': 'Variation Options',
                'ordering': ['type', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FabricZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Body, Lapel, Collar, Sleeve, Lining Body, Lining Sleeve', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabric_zones', to='orders.producttype')),
            ],
            options={
                'verbose_name': 'Fabric Zone',
                'verbose_name_plural': 'Fabric Zones',
                'ordering': ['product_type', 'order', 'name'],
                'unique_together': {('product_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FabricZoneEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_label', models.CharField(blank=True, help_text='Custom zone name (used when zone FK is blank).', max_length=100)),
                ('fabric_code', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('fabric_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_entries', to='orders.fabricset')),
                ('zone', models.ForeignKey(blank=True, help_text='Predefined zone. Leave blank to use custom zone label.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.fabriczone')),
            ],
            options={
                'verbose_name': 'Fabric Zone Entry',
                'verbose_name_plural': 'Fabric Zone Entries',
                'ordering': ['fabric_set', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ProductionBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('men', 'Men'), ('ladies', 'Ladies'), ('unisex', 'Unisex')], default='men', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='General notes for the factory.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_bills_confirmed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_bills_created', to=settings.AUTH_USER_MODEL)),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='production_bill', to='orders.orderitem')),
            ],
            options={
                'verbose_name': 'Production Bill',
                'verbose_name_plural': 'Production Bills',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='fabricset',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabric_sets', to='orders.productionbill'),
        ),
        migrations.CreateModel(
            name='Monogram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Initials e.g. "MML"', max_length=20)),
                ('color', models.CharField(blank=True, help_text='e.g. "Gold", "Navy Blue"', max_length=100)),
                ('position', models.CharField(blank=True, help_text='e.g. "Chest", "Cuff", "Collar"', max_length=100)),
                ('fabric_set', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monogram', to='orders.fabricset')),
                ('style', models.ForeignKey(blank=True, help_text='Style diagram option e.g. Script, Block, Old English', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monogram_uses', to='orders.variationoption')),
            ],
            options={
                'verbose_name': 'Monogram',
                'verbose_name_plural': 'Monograms',
            },
        ),
        migrations.CreateModel(
            name='VariationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('target_items', models.ManyToManyField(help_text='Which garment types this variation applies to.', related_name='variation_types', to='orders.targetitem')),
            ],
            options={
                'verbose_name': 'Variation Type',
                'verbose_name_plural': 'Variation Types',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='variationoption',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='orders.variationtype'),
        ),
        migrations.AlterUniqueTogether(
            name='fabricset',
            unique_together={('bill', 'piece_number')},
        ),
        migrations.AlterUniqueTogether(
            name='variationoption',
            unique_together={('type', 'name')},
        ),
        migrations.CreateModel(
            name='BillStyleSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_selections', to='orders.productionbill')),
                ('chosen_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_selections', to='orders.variationoption')),
                ('variation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_selections', to='orders.variationtype')),
            ],
            options={
                'verbose_name': 'Bill Style Selection',
                'verbose_name_plural': 'Bill Style Selections',
                'unique_together': {('bill', 'variation_type')},
            },
        ),
    ]
