# Generated by Django 5.2.11 on 2026-06-15 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_productionbill_sent_to_factory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('men', 'Men'), ('ladies', 'Ladies')], default='men', max_length=10)),
                ('neck', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Neck')),
                ('shoulder', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Shoulder')),
                ('sleeve', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Sleeve')),
                ('biceps', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Biceps')),
                ('chest', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Chest')),
                ('stomach', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Stomach')),
                ('waist', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Waist')),
                ('hips', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Hips')),
                ('height', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Height')),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Weight')),
                ('high_chest', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='High Chest')),
                ('upper_hips', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Upper Hips')),
                ('deep_front', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Deep Front')),
                ('deep_back', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Deep Back')),
                ('shoulder_to_middle_breast', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Shoulder to Middle Breast')),
                ('shoulder_to_under_breast', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Shoulder to Under Breast')),
                ('middle_breast_to_middle_breast', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Middle Breast to Middle Breast')),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='body_measurement', to='orders.orderitem')),
            ],
            options={
                'verbose_name': 'Body Measurement',
                'verbose_name_plural': 'Body Measurements',
            },
        ),
    ]
