# Generated by Django 5.2.11 on 2026-06-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_bodymeasurement'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clientphoto',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='clientphoto',
            name='person_number',
            field=models.PositiveIntegerField(default=1, help_text='Person 1, 2, 3... for package orders with multiple people.'),
        ),
        migrations.AlterUniqueTogether(
            name='clientphoto',
            unique_together={('order', 'person_number', 'photo_type')},
        ),
    ]
