# Generated by Django 5.2.11 on 2026-06-15 08:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_total_locked_order_total_locked_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.ImageField(upload_to='temp_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Temp Photo',
                'verbose_name_plural': 'Temp Photos',
            },
        ),
    ]
