# Generated by Django 5.2.11 on 2026-06-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_delivery_time_order_fitting_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodymeasurement',
            name='waist',
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='back',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Back'),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='crotch',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Crotch'),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='cuff',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Cuff'),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='front',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Front'),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='knee',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Knee'),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Length'),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='pants_hip',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Pants Hip'),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='pants_length',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Pants Length'),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='pants_waist',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Pants Waist'),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='shoulder_posture',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('slope', 'Slope'), ('square', 'Square')], max_length=10, null=True, verbose_name='Shoulder Posture'),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='thigh',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Thigh'),
        ),
        migrations.AlterField(
            model_name='bodymeasurement',
            name='hips',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Hip'),
        ),
    ]
