# Generated by Django 5.2.11 on 2026-06-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_remove_blousemeasurement_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstaff',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('salesman', 'Salesman'), ('helper', 'Helper')], default='salesman', max_length=20),
        ),
    ]
