# Generated by Django 5.2.11 on 2026-06-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_orderstaff_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='group_label',
            field=models.CharField(blank=True, help_text='e.g. "2-piece suit", "3-piece suit". Items with the same label are grouped together.', max_length=100, null=True, verbose_name='Set / Group'),
        ),
    ]
