# Generated by Django 5.2.11 on 2026-06-20 06:54
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_add_share_token_to_production_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodymeasurement',
            name='shoulder_to_back',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Shoulder to Back'),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='shoulder_to_waist',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Shoulder to Waist'),
        ),
    ]
