# Generated by Django 5.2.11 on 2026-06-22 13:57

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_client_birthday_exclude_from_marketing'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='favicon',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Browser tab icon (32x32 recommended)', max_length=255, null=True, verbose_name='favicon'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Shop logo shown in sidebar', max_length=255, null=True, verbose_name='logo'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='package',
            field=models.CharField(choices=[('studio', 'Studio only'), ('studio_catalogue', 'Studio + Catalogue')], default='studio', max_length=30),
        ),
    ]
