# Generated by Django 5.2.11 on 2026-06-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_tenant_logo_favicon_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='catalogue_subdomain',
            field=models.CharField(blank=True, default='', help_text='Catalogue subdomain e.g. sukhumvit → sukhumvit.catalogue.emporiumarmani.com', max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='has_catalogue',
            field=models.BooleanField(default=False, help_text='Shop has catalogue app enabled'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='whatsapp_phone_number_id',
            field=models.CharField(blank=True, default='', help_text='WhatsApp Phone Number ID from Meta Developer Dashboard', max_length=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='whatsapp_token',
            field=models.TextField(blank=True, default='', help_text='WhatsApp Business API permanent token'),
        ),
    ]
