# Generated by Django 5.2.11 on 2026-06-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_tenant_whatsapp_catalogue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='catalogue_subdomain',
            field=models.CharField(blank=True, default='', help_text='Catalogue subdomain e.g. sukhumvit → sukhumvit.catalogue.emporiumarmani.com', max_length=100),
        ),
    ]
