# Generated by Django 5.2.11 on 2026-06-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_tenant_custom_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='external_order_number',
            field=models.CharField(blank=True, db_index=True, help_text='Existing order number from previous system (optional)', max_length=50, null=True),
        ),
    ]
