# Generated by Django 5.2.11 on 2026-06-26 09:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_order_external_order_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('external_order_number__isnull', False), models.Q(('external_order_number', ''), _negated=True)), fields=('tenant', 'external_order_number'), name='unique_external_order_number_per_tenant'),
        ),
    ]
