# Generated by Django 5.2.11 on 2026-06-27 07:28

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_order_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='fabric_code',
            field=models.CharField(blank=True, default='', help_text='Fabric code (plain text — used when fabric library is disabled)', max_length=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='has_fabric_library',
            field=models.BooleanField(default=False, help_text='Enable fabric library (paid add-on)'),
        ),
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_article', models.CharField(db_index=True, help_text='SKU / Article code e.g. GT5258', max_length=50)),
                ('name', models.CharField(help_text='Fabric name e.g. Gray Plain', max_length=255)),
                ('brand', models.CharField(blank=True, default='', max_length=100)),
                ('composition', models.CharField(blank=True, default='', help_text='e.g. 100% Wool (Super 150S)', max_length=200)),
                ('weight', models.CharField(blank=True, default='', help_text='e.g. 280 g.', max_length=50)),
                ('width', models.CharField(blank=True, default='', help_text='e.g. 60 in or 136 cm.', max_length=50)),
                ('pattern', models.CharField(blank=True, default='', help_text='e.g. Plain, Stripe, Check, Print', max_length=100)),
                ('colour', models.CharField(blank=True, default='', max_length=200)),
                ('collection', models.CharField(blank=True, default='', max_length=100)),
                ('details', models.TextField(blank=True, default='')),
                ('price_per_metre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='fabric_image')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabrics', to='orders.tenant')),
            ],
            options={
                'verbose_name': 'Fabric',
                'verbose_name_plural': 'Fabrics',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fabric',
            field=models.ForeignKey(blank=True, help_text='Fabric from library (used when fabric library is enabled)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='orders.fabric'),
        ),
        migrations.CreateModel(
            name='FabricCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('suiting', 'Suiting'), ('shirting', 'Shirting'), ('trousering', 'Trousering'), ('lining', 'Lining'), ('other', 'Other')], max_length=50)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabric_categories', to='orders.tenant')),
            ],
            options={
                'verbose_name': 'Fabric Category',
                'verbose_name_plural': 'Fabric Categories',
                'ordering': ['name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.AddField(
            model_name='fabric',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fabrics', to='orders.fabriccategory'),
        ),
        migrations.AlterUniqueTogether(
            name='fabric',
            unique_together={('tenant', 'sku_article')},
        ),
    ]
