# Generated by Django 5.2.11 on 2026-06-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_fabric_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabriccategory',
            name='name',
            field=models.CharField(choices=[('suiting', 'Suiting'), ('shirting', 'Shirting'), ('sport_coats', 'Sport Coats'), ('overcoats', 'Overcoats'), ('trousering', 'Trousering'), ('lining', 'Lining'), ('other', 'Other')], max_length=50),
        ),
    ]
