# Generated by Django 5.2.11 on 2026-06-30 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_alter_fabriccategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_exchange_rate_to_thb',
            field=models.DecimalField(decimal_places=6, default=1, help_text="Exchange rate to THB at time total was set. THB=1. Crypto=agreed fixed rate. Others=today's rate.", max_digits=12),
        ),
    ]
