# Generated by Django 5.2.11 on 2026-06-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_order_total_exchange_rate_to_thb'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Shop contact phone (shown on shipping labels, invoices)', max_length=30),
        ),
        migrations.AddField(
            model_name='tenant',
            name='postcode',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='street_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
