# Generated by Django 5.2.11 on 2026-06-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_tenant_city_tenant_country_tenant_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_3mo_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='return_6mo_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
