# Generated by Django 5.2.11 on 2026-09-19 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_order_return_3mo_notified_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='client',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='The shop this client belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='orders.tenant'),
        ),
    ]
