# Generated by Django 5.2.11 on 2026-09-20 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_client_tenant_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, help_text='Actual order date — use when entering historical orders from order books. Leave blank to use today.', null=True),
        ),
    ]
