# Generated by Django 5.2.11 on 2026-09-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_whatsapp_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='media_type',
            field=models.CharField(blank=True, default='', help_text='image/document/video/audio', max_length=20),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='media_url',
            field=models.URLField(blank=True, default='', help_text='URL of media file (image/document/video)'),
        ),
    ]
